### ISSUE TITLE
Derivans Failure METS

### ISSUE THREAD

**Issue by M3ssman** [ulb-sachsen-anhalt/digital-derivans#35]
# Description

For some rather seldom constellations when only one logical section is present, Derivans fails to decide which one the main section actually is

```
2022-10-18 15:48:05 [INFO ][main](DerivansConfiguration:193) reconfigured application logging using '/usr/local/kitodo/ulb-scripts/bin/config/derivans_logging.xml'
2022-10-18 15:48:05 [INFO ][main](DerivansConfiguration:283) set footer template '/usr/local/kitodo/ulb-scripts/bin/config/footer_template.png'
2022-10-18 15:48:05 [INFO ][main](Derivans:99) set derivates pathDir: '/var/lib/tomcat9/kitodo-hotfolder/work_1748529021', metsFile: '/var/lib/tomcat9/kitodo-hotfolder/work_1748529021/1748529021.xml'
Exception in thread "main" de.ulb.digital.derivans.DigitalDerivansException: de.ulb.digital.derivans.DigitalDerivansException: can't identify primary MODS section
	at de.ulb.digital.derivans.data.MetadataHandler.<init>(MetadataHandler.java:73)
	at de.ulb.digital.derivans.data.MetadataStore.<init>(MetadataStore.java:74)
	at de.ulb.digital.derivans.Derivans.<init>(Derivans.java:100)
	at de.ulb.digital.derivans.App.main(App.java:37)
Caused by: de.ulb.digital.derivans.DigitalDerivansException: can't identify primary MODS section
	at de.ulb.digital.derivans.data.MetadataHandler.setPrimaryMods(MetadataHandler.java:251)
	at de.ulb.digital.derivans.data.MetadataHandler.<init>(MetadataHandler.java:71)
	... 3 more
```

**Comment by M3ssman** [comment]
unexpected METS attached
[1748529021.zip](https://github.com/ulb-sachsen-anhalt/digital-derivans/files/9817072/1748529021.zip)

**Comment by sVnsation** [comment]
Suggestion from @ulb-sa-schmilj in case of equality in mets:structLink -> check which ID is higher in the tree at mets:structMap TYPE="LOGICAL"

for example, result in this case is LOG_0000:

```
<mets:structLink>
    <mets:smLink xlink:to="PHYS_0001" xlink:from="LOG_0000" xmlns:xlink="http://www.w3.org/1999/xlink"/>
    <mets:smLink xlink:to="PHYS_0002" xlink:from="LOG_0000" xmlns:xlink="http://www.w3.org/1999/xlink"/>
    <mets:smLink xlink:to="PHYS_0003" xlink:from="LOG_0000" xmlns:xlink="http://www.w3.org/1999/xlink"/>
    <mets:smLink xlink:to="PHYS_0001" xlink:from="LOG_0001" xmlns:xlink="http://www.w3.org/1999/xlink"/>
    <mets:smLink xlink:to="PHYS_0002" xlink:from="LOG_0001" xmlns:xlink="http://www.w3.org/1999/xlink"/>
    <mets:smLink xlink:to="PHYS_0003" xlink:from="LOG_0001" xmlns:xlink="http://www.w3.org/1999/xlink"/>
</mets:structLink>

<mets:structMap TYPE="LOGICAL">
    <mets:div  ID="LOG_0000"">
        <mets:div ID="LOG_0001">
    </mets:div>
</mets:structMap>
```

**Comment by M3ssman** [comment]
Sounds reasonable. 
I can fancy to combine this with an approach to simply count the unique linked structures.
Looks like this only happens when there are just 2 linked logical containers. 
It can't turn into an issue with more containers, since in this scenario the main logical container must always have more links than any of it's children. Going this direction will also spare the existing, battle-tested and working approach from any disturbances.
